## Setup

In [1]:
from utils import fs_utils as fs

output_directory = fs.resolve_output_directory()
display(output_directory)

PosixPath('/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/data/out')

## Linear regression

In [ ]:
from ml.datasets import build_activity_value_regression_dataset
from ml.sklearn_workflows import run_linear_regression

regression_dataset = build_activity_value_regression_dataset()
display(regression_dataset)
regression_dataset.frame.to_csv(output_directory / "cid4_ml.bioactivity_regression_features.csv", index=False)
linear_regression = run_linear_regression(regression_dataset)
linear_regression

PreparedDataset(name='bioactivity-activity-value-regression', task_type='regression', frame=   Bioactivity_ID      Aid_Type     Activity Protein_Accession Activity_Type  \
0       334754348  Confirmatory  Unspecified          AEP43755       Potency
1       100909607  Confirmatory        Probe               NaN          IC50

  Activity_Qualifier Bioassay_Data_Source  \
0                NaN                Tox21
1                  =               ChEMBL

                                       BioAssay_Name       Compound_Name  \
0  qHTS assay to identify small molecule antagoni...  1-Amino-2-propanol
1  Inhibitory activity against Plasmodium falciparum  1-Amino-2-propanol

                                         Target_Name  ...  \
0                 ESR1 - estrogen receptor 1 (human)  ...
1  Plasmodium falciparum (malaria parasite P. fal...  ...

  BioAssay_Name_Has_Plasmodium BioAssay_Name_Has_Yeast  \
0                            0                       0
1                            1                       0

  Target_Name_Has_Estrogen  Target_Name_Has_Androgen  \
0                        1                         0
1                        0                         0

   Target_Name_Has_Cytochrome Target_Name_Has_Plasmodium  \
0                           0                          0
1                           0                          1

   Target_Name_Has_Yeast  Bioassay_Source_Has_Tox21  \
0                      0                          1
1                      0                          0

  Bioassay_Source_Has_ChEMBL  Bioassay_Source_Has_DTP_NCI
0                          0                            0
1                          1                            0

[2 rows x 64 columns], feature_columns=['C_count', 'H_count', 'N_count', 'O_count', 'bond_count_total', 'mol_weight', 'has_chiral_center', 'Aid_Type_Encoded', 'Activity_Type_Encoded', 'Bioassay_Data_Source_Encoded', 'Has_Dose_Response_Curve', 'RNAi_BioAssay', 'Taxonomy_ID_Numeric', 'Target_Taxonomy_ID_Numeric', 'Has_Protein_Accession', 'Has_Gene_ID', 'Has_PMID', 'Has_Activity_Value', 'BioAssay_Name_Has_qHTS', 'BioAssay_Name_Has_IC50', 'BioAssay_Name_Has_Counter_Screen', 'BioAssay_Name_Has_Estrogen', 'BioAssay_Name_Has_Androgen', 'BioAssay_Name_Has_Cytochrome', 'BioAssay_Name_Has_Plasmodium', 'BioAssay_Name_Has_Yeast', 'Target_Name_Has_Estrogen', 'Target_Name_Has_Androgen', 'Target_Name_Has_Cytochrome', 'Target_Name_Has_Plasmodium', 'Target_Name_Has_Yeast', 'Bioassay_Source_Has_Tox21', 'Bioassay_Source_Has_ChEMBL', 'Bioassay_Source_Has_DTP_NCI'], target_column='Activity_Value', description='Positive numeric Activity_Value regression dataset using molecular descriptors and assay metadata.', class_names=None)

{'dataset': {'name': 'bioactivity-activity-value-regression',
  'task_type': 'regression',
  'row_count': 2,
  'feature_count': 34,
  'feature_columns': ['C_count',
   'H_count',
   'N_count',
   'O_count',
   'bond_count_total',
   'mol_weight',
   'has_chiral_center',
   'Aid_Type_Encoded',
   'Activity_Type_Encoded',
   'Bioassay_Data_Source_Encoded',
   'Has_Dose_Response_Curve',
   'RNAi_BioAssay',
   'Taxonomy_ID_Numeric',
   'Target_Taxonomy_ID_Numeric',
   'Has_Protein_Accession',
   'Has_Gene_ID',
   'Has_PMID',
   'Has_Activity_Value',
   'BioAssay_Name_Has_qHTS',
   'BioAssay_Name_Has_IC50',
   'BioAssay_Name_Has_Counter_Screen',
   'BioAssay_Name_Has_Estrogen',
   'BioAssay_Name_Has_Androgen',
   'BioAssay_Name_Has_Cytochrome',
   'BioAssay_Name_Has_Plasmodium',
   'BioAssay_Name_Has_Yeast',
   'Target_Name_Has_Estrogen',
   'Target_Name_Has_Androgen',
   'Target_Name_Has_Cytochrome',
   'Target_Name_Has_Plasmodium',
   'Target_Name_Has_Yeast',
   'Bioassay_Source_Has_Tox21',
   'Bioassay_Source_Has_ChEMBL',
   'Bioassay_Source_Has_DTP_NCI'],
  'target_column': 'Activity_Value',
  'class_names': None,
  'description': 'Positive numeric Activity_Value regression dataset using molecular descriptors and assay metadata.'},
 'evaluation_note': 'Dataset is too small for a stable holdout split, so evaluation is reported on the training rows.',
 'manual_normal_equation': {'equation': 'w = (X^T X)^+ X^T y',
  'intercept': 9.31773629281119e-06,
  'coefficients': [2.7953208878421278e-05,
   8.385962663531533e-05,
   9.317736292811188e-06,
   9.317736292811188e-06,
   0.0001211305718065455,
   0.000699864490689341,
   9.317736292811188e-06,
   0.0,
   -1.3799385285032556e-05,
   -1.3799385285032556e-05,
   -1.3799385285032556e-05,
   0.0,
   0.0022852751155397876,
   0.13485596954884765,
   -1.3799385285032556e-05,
   -1.3799385285032556e-05,
   2.3117121577843752e-05,
   9.317736292811188e-06,
   -1.3799385285032556e-05,
   0.0,
   0.0,
   -1.3799385285032556e-05,
   0.0,
   0.0,
   2.3117121577843752e-05,
   0.0,
   -1.3799385285032556e-05,
   0.0,
   0.0,
   2.3117121577843752e-05,
   0.0,
   -1.3799385285032556e-05,
   2.3117121577843752e-05,
   0.0]},
 'sklearn_linear_regression': {'intercept': 606.2089325200517,
  'coefficients': [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   -1.61199482141467e-05,
   -1.61199482141467e-05,
   -1.61199482141467e-05,
   0.0,
   -0.06082056461197549,
   0.09404377788133184,
   -1.61199482141467e-05,
   -1.61199482141467e-05,
   1.61199482141467e-05,
   0.0,
   -1.61199482141467e-05,
   0.0,
   0.0,
   -1.61199482141467e-05,
   0.0,
   0.0,
   1.61199482141467e-05,
   0.0,
   -1.61199482141467e-05,
   0.0,
   0.0,
   1.61199482141467e-05,
   0.0,
   -1.61199482141467e-05,
   1.61199482141467e-05,
   0.0]},
 'metrics': {'mae': 1.2789769243681803e-13,
  'rmse': 1.2868476258827026e-13,
  'r2': 1.0}}

## Activity value regression

In [1]:
from ml.datasets import build_activity_value_regression_dataset

regression_dataset = build_activity_value_regression_dataset()

### XGBoost regression

In [ ]:
from ml.xgboost_workflows import run_xgboost_regression

run_xgboost_regression(regression_dataset)

{'library': 'xgboost',
 'dataset': {'name': 'bioactivity-activity-value-regression',
  'task_type': 'regression',
  'row_count': 2,
  'feature_count': 34,
  'feature_columns': ['C_count',
   'H_count',
   'N_count',
   'O_count',
   'bond_count_total',
   'mol_weight',
   'has_chiral_center',
   'Aid_Type_Encoded',
   'Activity_Type_Encoded',
   'Bioassay_Data_Source_Encoded',
   'Has_Dose_Response_Curve',
   'RNAi_BioAssay',
   'Taxonomy_ID_Numeric',
   'Target_Taxonomy_ID_Numeric',
   'Has_Protein_Accession',
   'Has_Gene_ID',
   'Has_PMID',
   'Has_Activity_Value',
   'BioAssay_Name_Has_qHTS',
   'BioAssay_Name_Has_IC50',
   'BioAssay_Name_Has_Counter_Screen',
   'BioAssay_Name_Has_Estrogen',
   'BioAssay_Name_Has_Androgen',
   'BioAssay_Name_Has_Cytochrome',
   'BioAssay_Name_Has_Plasmodium',
   'BioAssay_Name_Has_Yeast',
   'Target_Name_Has_Estrogen',
   'Target_Name_Has_Androgen',
   'Target_Name_Has_Cytochrome',
   'Target_Name_Has_Plasmodium',
   'Target_Name_Has_Yeast',
   'Bioassay_Source_Has_Tox21',
   'Bioassay_Source_Has_ChEMBL',
   'Bioassay_Source_Has_DTP_NCI'],
  'target_column': 'Activity_Value',
  'class_names': None,
  'description': 'Positive numeric Activity_Value regression dataset using molecular descriptors and assay metadata.'},
 'evaluation_note': 'Dataset is too small for a stable holdout split, so evaluation is reported on the training rows.',
 'metrics': {'mae': 1.4825946319580083,
  'rmse': 1.4825946328244406,
  'r2': 0.9999854787768722},
 'feature_importances': [{'feature': 'Bioassay_Data_Source_Encoded',
   'importance': 0.45788243412971497},
  {'feature': 'Activity_Type_Encoded', 'importance': 0.4534922242164612},
  {'feature': 'Has_Dose_Response_Curve', 'importance': 0.08845918625593185},
  {'feature': 'Taxonomy_ID_Numeric', 'importance': 0.0001661683345446363},
  {'feature': 'C_count', 'importance': 0.0},
  {'feature': 'H_count', 'importance': 0.0},
  {'feature': 'N_count', 'importance': 0.0},
  {'feature': 'O_count', 'importance': 0.0},
  {'feature': 'bond_count_total', 'importance': 0.0},
  {'feature': 'mol_weight', 'importance': 0.0},
  {'feature': 'has_chiral_center', 'importance': 0.0},
  {'feature': 'Aid_Type_Encoded', 'importance': 0.0},
  {'feature': 'RNAi_BioAssay', 'importance': 0.0},
  {'feature': 'Target_Taxonomy_ID_Numeric', 'importance': 0.0},
  {'feature': 'Has_Protein_Accession', 'importance': 0.0},
  {'feature': 'Has_Gene_ID', 'importance': 0.0},
  {'feature': 'Has_PMID', 'importance': 0.0},
  {'feature': 'Has_Activity_Value', 'importance': 0.0},
  {'feature': 'BioAssay_Name_Has_qHTS', 'importance': 0.0},
  {'feature': 'BioAssay_Name_Has_IC50', 'importance': 0.0},
  {'feature': 'BioAssay_Name_Has_Counter_Screen', 'importance': 0.0},
  {'feature': 'BioAssay_Name_Has_Estrogen', 'importance': 0.0},
  {'feature': 'BioAssay_Name_Has_Androgen', 'importance': 0.0},
  {'feature': 'BioAssay_Name_Has_Cytochrome', 'importance': 0.0},
  {'feature': 'BioAssay_Name_Has_Plasmodium', 'importance': 0.0},
  {'feature': 'BioAssay_Name_Has_Yeast', 'importance': 0.0},
  {'feature': 'Target_Name_Has_Estrogen', 'importance': 0.0},
  {'feature': 'Target_Name_Has_Androgen', 'importance': 0.0},
  {'feature': 'Target_Name_Has_Cytochrome', 'importance': 0.0},
  {'feature': 'Target_Name_Has_Plasmodium', 'importance': 0.0},
  {'feature': 'Target_Name_Has_Yeast', 'importance': 0.0},
  {'feature': 'Bioassay_Source_Has_Tox21', 'importance': 0.0},
  {'feature': 'Bioassay_Source_Has_ChEMBL', 'importance': 0.0},
  {'feature': 'Bioassay_Source_Has_DTP_NCI', 'importance': 0.0}],
 'model_parameters': {'n_estimators': 220,
  'max_depth': 4,
  'learning_rate': 0.05,
  'objective': 'reg:squarederror'}}

### PyTorch regression

In [1]:
import torch

torch.__version__

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 577, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3116, in run_cell
    result = self._run_cell(
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3171, in _run_cell
    result = runner(coro)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3394, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3639, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3699, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/kr/drklfx3s76ldd7v9jv96hf1h0000gn/T/ipykernel_26408/335528599.py", line 1, in <module>
    import torch
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1711403213615/work/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),

'2.2.2'

In [3]:
from ml.torch_workflows import run_torch_regression

run_torch_regression(regression_dataset)

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 577, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3116, in run_cell
    result = self._run_cell(
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3171, in _run_cell
    result = runner(coro)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3394, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3639, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3699, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/kr/drklfx3s76ldd7v9jv96hf1h0000gn/T/ipykernel_64602/726205007.py", line 1, in <module>
    from ml.torch_workflows import run_torch_regression
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/src/ml/torch_workflows.py", line 4, in <module>
    import torch
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1711403213615/work/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),

RuntimeError: Numpy is not available

### TensorFlow regression

In [2]:
import tensorflow as tf

tf.__version__

2026-04-16 22:22:08.490947: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

'2.18.0'

In [ ]:
from ml.tensorflow_workflows import run_tensorflow_regression

run_tensorflow_regression(regression_dataset)

2026-04-16 19:59:54.671925: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

{'library': 'tensorflow',
 'dataset': {'name': 'bioactivity-activity-value-regression',
  'task_type': 'regression',
  'row_count': 2,
  'feature_count': 34,
  'feature_columns': ['C_count',
   'H_count',
   'N_count',
   'O_count',
   'bond_count_total',
   'mol_weight',
   'has_chiral_center',
   'Aid_Type_Encoded',
   'Activity_Type_Encoded',
   'Bioassay_Data_Source_Encoded',
   'Has_Dose_Response_Curve',
   'RNAi_BioAssay',
   'Taxonomy_ID_Numeric',
   'Target_Taxonomy_ID_Numeric',
   'Has_Protein_Accession',
   'Has_Gene_ID',
   'Has_PMID',
   'Has_Activity_Value',
   'BioAssay_Name_Has_qHTS',
   'BioAssay_Name_Has_IC50',
   'BioAssay_Name_Has_Counter_Screen',
   'BioAssay_Name_Has_Estrogen',
   'BioAssay_Name_Has_Androgen',
   'BioAssay_Name_Has_Cytochrome',
   'BioAssay_Name_Has_Plasmodium',
   'BioAssay_Name_Has_Yeast',
   'Target_Name_Has_Estrogen',
   'Target_Name_Has_Androgen',
   'Target_Name_Has_Cytochrome',
   'Target_Name_Has_Plasmodium',
   'Target_Name_Has_Yeast',
   'Bioassay_Source_Has_Tox21',
   'Bioassay_Source_Has_ChEMBL',
   'Bioassay_Source_Has_DTP_NCI'],
  'target_column': 'Activity_Value',
  'class_names': None,
  'description': 'Positive numeric Activity_Value regression dataset using molecular descriptors and assay metadata.'},
 'evaluation_note': 'Dataset is too small for a stable holdout split, so evaluation is reported on the training rows.',
 'epochs': 300,
 'metrics': {'mae': 388.5279930603027,
  'rmse': 547.2412308215719,
  'r2': -0.9784085195146586}}

## Logistic regression

In [6]:
from ml.sklearn_workflows import run_logistic_regression

In [ ]:
from ml.datasets import build_atom_heavy_atom_dataset

atom_heavy_dataset = build_atom_heavy_atom_dataset()
display(atom_heavy_dataset)
atom_heavy_dataset.frame.to_csv(output_directory / "cid4_ml.atom_heavy_binary_features.csv", index=False)
heavy_atom_logistic_regression = run_logistic_regression(atom_heavy_dataset)
heavy_atom_logistic_regression

In [ ]:
from ml.datasets import build_atom_element_dataset

atom_element_dataset = build_atom_element_dataset()
display(atom_element_dataset)
atom_element_dataset.frame.to_csv(output_directory / "cid4_ml.atom_element_binary_features.csv", index=False)
atom_element_logistic_regression = run_logistic_regression(atom_element_dataset)
atom_element_logistic_regression

In [ ]:
from ml.datasets import build_bioactivity_binary_classification_dataset

bioactivity_dataset = build_bioactivity_binary_classification_dataset()
display(bioactivity_dataset)
bioactivity_dataset.frame.to_csv(output_directory / "cid4_ml.bioactivity_binary_features.csv", index=False)
logistic_regression = run_logistic_regression(bioactivity_dataset)
logistic_regression

PreparedDataset(name='bioactivity-active-vs-inactive', task_type='classification', frame=   Bioactivity_ID Aid_Type Activity Protein_Accession Activity_Type  \
0        32761399    Other   Active               NaN       Unknown
1       351848396    Other   Active               NaN       Unknown
2       351848428    Other   Active               NaN       Unknown

  Activity_Qualifier                               Bioassay_Data_Source  \
0                NaN                                         EPA DSSTox
1                NaN  Chemical Carcinogenesis Research Information S...
2                NaN  Chemical Carcinogenesis Research Information S...

                                       BioAssay_Name       Compound_Name  \
0  DSSTox (EPAFHM) EPA Fathead Minnow Acute Toxicity  1-Amino-2-propanol
1                         CCRIS mutagenicity studies  1-Amino-2-propanol
2                         CCRIS mutagenicity studies  1-Amino-2-propanol

  Target_Name  ... BioAssay_Name_Has_Yeast Target_Name_Has_Estrogen  \
0     Unknown  ...                       0                        0
1     Unknown  ...                       0                        0
2     Unknown  ...                       0                        0

  Target_Name_Has_Androgen  Target_Name_Has_Cytochrome  \
0                        0                           0
1                        0                           0
2                        0                           0

   Target_Name_Has_Plasmodium Target_Name_Has_Yeast  \
0                           0                     0
1                           0                     0
2                           0                     0

   Bioassay_Source_Has_Tox21  Bioassay_Source_Has_ChEMBL  \
0                          0                           0
1                          0                           0
2                          0                           0

  Bioassay_Source_Has_DTP_NCI  activityBinary
0                           0               1
1                           0               1
2                           0               1

[3 rows x 65 columns], feature_columns=['C_count', 'H_count', 'N_count', 'O_count', 'bond_count_total', 'mol_weight', 'has_chiral_center', 'Aid_Type_Encoded', 'Activity_Type_Encoded', 'Bioassay_Data_Source_Encoded', 'Has_Dose_Response_Curve', 'RNAi_BioAssay', 'Taxonomy_ID_Numeric', 'Target_Taxonomy_ID_Numeric', 'Has_Protein_Accession', 'Has_Gene_ID', 'Has_PMID', 'Has_Activity_Value', 'BioAssay_Name_Has_qHTS', 'BioAssay_Name_Has_IC50', 'BioAssay_Name_Has_Counter_Screen', 'BioAssay_Name_Has_Estrogen', 'BioAssay_Name_Has_Androgen', 'BioAssay_Name_Has_Cytochrome', 'BioAssay_Name_Has_Plasmodium', 'BioAssay_Name_Has_Yeast', 'Target_Name_Has_Estrogen', 'Target_Name_Has_Androgen', 'Target_Name_Has_Cytochrome', 'Target_Name_Has_Plasmodium', 'Target_Name_Has_Yeast', 'Bioassay_Source_Has_Tox21', 'Bioassay_Source_Has_ChEMBL', 'Bioassay_Source_Has_DTP_NCI'], target_column='activityBinary', description='Filtered Active vs Inactive assay rows using constant molecular descriptors and assay metadata.', class_names=['inactive', 'active'])

{'status': 'insufficient_data',
 'dataset': {'name': 'bioactivity-active-vs-inactive',
  'task_type': 'classification',
  'row_count': 3,
  'feature_count': 34,
  'feature_columns': ['C_count',
   'H_count',
   'N_count',
   'O_count',
   'bond_count_total',
   'mol_weight',
   'has_chiral_center',
   'Aid_Type_Encoded',
   'Activity_Type_Encoded',
   'Bioassay_Data_Source_Encoded',
   'Has_Dose_Response_Curve',
   'RNAi_BioAssay',
   'Taxonomy_ID_Numeric',
   'Target_Taxonomy_ID_Numeric',
   'Has_Protein_Accession',
   'Has_Gene_ID',
   'Has_PMID',
   'Has_Activity_Value',
   'BioAssay_Name_Has_qHTS',
   'BioAssay_Name_Has_IC50',
   'BioAssay_Name_Has_Counter_Screen',
   'BioAssay_Name_Has_Estrogen',
   'BioAssay_Name_Has_Androgen',
   'BioAssay_Name_Has_Cytochrome',
   'BioAssay_Name_Has_Plasmodium',
   'BioAssay_Name_Has_Yeast',
   'Target_Name_Has_Estrogen',
   'Target_Name_Has_Androgen',
   'Target_Name_Has_Cytochrome',
   'Target_Name_Has_Plasmodium',
   'Target_Name_Has_Yeast',
   'Bioassay_Source_Has_Tox21',
   'Bioassay_Source_Has_ChEMBL',
   'Bioassay_Source_Has_DTP_NCI'],
  'target_column': 'activityBinary',
  'class_names': ['inactive', 'active'],
  'description': 'Filtered Active vs Inactive assay rows using constant molecular descriptors and assay metadata.'},
 'reason': 'Logistic regression requires at least two target classes.',
 'observed_class_count': 1}

## Bioactivity binary classification

In [1]:
from ml.datasets import build_bioactivity_binary_classification_dataset

bioactivity_dataset = build_bioactivity_binary_classification_dataset()

### XGBoost classification

In [3]:
from ml.xgboost_workflows import run_xgboost_classification

xgboost_result = run_xgboost_classification(bioactivity_dataset)
xgboost_result

{'status': 'insufficient_data',
 'library': 'xgboost',
 'dataset': {'name': 'bioactivity-active-vs-inactive',
  'task_type': 'classification',
  'row_count': 3,
  'feature_count': 34,
  'feature_columns': ['C_count',
   'H_count',
   'N_count',
   'O_count',
   'bond_count_total',
   'mol_weight',
   'has_chiral_center',
   'Aid_Type_Encoded',
   'Activity_Type_Encoded',
   'Bioassay_Data_Source_Encoded',
   'Has_Dose_Response_Curve',
   'RNAi_BioAssay',
   'Taxonomy_ID_Numeric',
   'Target_Taxonomy_ID_Numeric',
   'Has_Protein_Accession',
   'Has_Gene_ID',
   'Has_PMID',
   'Has_Activity_Value',
   'BioAssay_Name_Has_qHTS',
   'BioAssay_Name_Has_IC50',
   'BioAssay_Name_Has_Counter_Screen',
   'BioAssay_Name_Has_Estrogen',
   'BioAssay_Name_Has_Androgen',
   'BioAssay_Name_Has_Cytochrome',
   'BioAssay_Name_Has_Plasmodium',
   'BioAssay_Name_Has_Yeast',
   'Target_Name_Has_Estrogen',
   'Target_Name_Has_Androgen',
   'Target_Name_Has_Cytochrome',
   'Target_Name_Has_Plasmodium',
   'Target_Name_Has_Yeast',
   'Bioassay_Source_Has_Tox21',
   'Bioassay_Source_Has_ChEMBL',
   'Bioassay_Source_Has_DTP_NCI'],
  'target_column': 'activityBinary',
  'class_names': ['inactive', 'active'],
  'description': 'Filtered Active vs Inactive assay rows using constant molecular descriptors and assay metadata.'},
 'reason': 'XGBoost classification requires at least two target classes.',
 'observed_class_count': 1}

### Tensorflow classification

In [2]:
from ml.tensorflow_workflows import run_tensorflow_classification

tensorflow_classification_result = run_tensorflow_classification(bioactivity_dataset)
tensorflow_classification_result

2026-04-17 10:34:08.605324: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

{'status': 'insufficient_data',
 'library': 'tensorflow',
 'dataset': {'name': 'bioactivity-active-vs-inactive',
  'task_type': 'classification',
  'row_count': 3,
  'feature_count': 34,
  'feature_columns': ['C_count',
   'H_count',
   'N_count',
   'O_count',
   'bond_count_total',
   'mol_weight',
   'has_chiral_center',
   'Aid_Type_Encoded',
   'Activity_Type_Encoded',
   'Bioassay_Data_Source_Encoded',
   'Has_Dose_Response_Curve',
   'RNAi_BioAssay',
   'Taxonomy_ID_Numeric',
   'Target_Taxonomy_ID_Numeric',
   'Has_Protein_Accession',
   'Has_Gene_ID',
   'Has_PMID',
   'Has_Activity_Value',
   'BioAssay_Name_Has_qHTS',
   'BioAssay_Name_Has_IC50',
   'BioAssay_Name_Has_Counter_Screen',
   'BioAssay_Name_Has_Estrogen',
   'BioAssay_Name_Has_Androgen',
   'BioAssay_Name_Has_Cytochrome',
   'BioAssay_Name_Has_Plasmodium',
   'BioAssay_Name_Has_Yeast',
   'Target_Name_Has_Estrogen',
   'Target_Name_Has_Androgen',
   'Target_Name_Has_Cytochrome',
   'Target_Name_Has_Plasmodium',
   'Target_Name_Has_Yeast',
   'Bioassay_Source_Has_Tox21',
   'Bioassay_Source_Has_ChEMBL',
   'Bioassay_Source_Has_DTP_NCI'],
  'target_column': 'activityBinary',
  'class_names': ['inactive', 'active'],
  'description': 'Filtered Active vs Inactive assay rows using constant molecular descriptors and assay metadata.'},
 'reason': 'TensorFlow classification requires at least two target classes.'}

## PyTorch bioactivity binary classification

In [ ]:
from ml.torch_workflows import run_torch_classification
from ml.datasets import build_bioactivity_binary_classification_dataset

bioactivity_dataset = build_bioactivity_binary_classification_dataset()
run_torch_classification(bioactivity_dataset)

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/asyncio/base_events.py", line 645, in run_forever
    self._run_once()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/asyncio/base_events.py", line 1999, in _run_once
    handle._run()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 577, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3116, in run_cell
    result = self._run_cell(
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3171, in _run_cell
    result = runner(coro)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3394, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3639, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3699, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/kr/drklfx3s76ldd7v9jv96hf1h0000gn/T/ipykernel_62205/3729691917.py", line 1, in <module>
    from ml.torch_workflows import run_torch_classification
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/src/ml/torch_workflows.py", line 4, in <module>
    import torch
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/.venv/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1711403213615/work/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),

ImportError: cannot import name 'run_torch_classification' from 'ml.torch_workflows' (/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/src/ml/torch_workflows.py)

## PyTorch atom element multiclass classification

In [2]:
from ml.datasets import build_atom_element_dataset
from ml.torch_workflows import run_torch_classification

atom_element_dataset = build_atom_element_dataset()
run_torch_classification(atom_element_dataset)

ImportError: cannot import name 'run_torch_classification' from 'ml.torch_workflows' (/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/src/ml/torch_workflows.py)

# PyTorch heavy atom vs hydrogen

In [3]:
from ml.datasets import build_atom_heavy_atom_dataset
from ml.torch_workflows import run_torch_classification

atom_heavy_dataset = build_atom_heavy_atom_dataset()
run_torch_classification(atom_heavy_dataset)

ImportError: cannot import name 'run_torch_classification' from 'ml.torch_workflows' (/Users/Artsem_Nikitsenka/projects/pubchem-cid4-analysis/py/src/ml/torch_workflows.py)

## Heavy atom classification

In [2]:
from ml.tensorflow_workflows import run_tensorflow_classification

2026-04-17 11:29:29.975807: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [ ]:
from ml.datasets import build_atom_heavy_atom_dataset

atom_heavy_dataset = build_atom_heavy_atom_dataset()
run_tensorflow_classification(atom_heavy_dataset)

2026-04-17 10:50:16.228613: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

:

:

:

In [3]:
from ml.datasets import build_atom_element_dataset

atom_element_dataset = build_atom_element_dataset()
run_tensorflow_classification(atom_element_dataset)

:

:

:

## SVM

In [10]:
from ml.datasets import build_bioactivity_binary_classification_dataset
from ml.sklearn_workflows import run_svm

bioactivity_dataset = build_bioactivity_binary_classification_dataset()
display(bioactivity_dataset)
bioactivity_dataset.frame.to_csv(output_directory / "cid4_ml.bioactivity_svm_features.csv", index=False)
svm_result = run_svm(bioactivity_dataset)
svm_result

PreparedDataset(name='bioactivity-active-vs-inactive', task_type='classification', frame=   Bioactivity_ID Aid_Type Activity Protein_Accession Activity_Type  \
0        32761399    Other   Active               NaN       Unknown
1       351848396    Other   Active               NaN       Unknown
2       351848428    Other   Active               NaN       Unknown

  Activity_Qualifier                               Bioassay_Data_Source  \
0                NaN                                         EPA DSSTox
1                NaN  Chemical Carcinogenesis Research Information S...
2                NaN  Chemical Carcinogenesis Research Information S...

                                       BioAssay_Name       Compound_Name  \
0  DSSTox (EPAFHM) EPA Fathead Minnow Acute Toxicity  1-Amino-2-propanol
1                         CCRIS mutagenicity studies  1-Amino-2-propanol
2                         CCRIS mutagenicity studies  1-Amino-2-propanol

  Target_Name  ... BioAssay_Name_Has_Yeast Target_Name_Has_Estrogen  \
0     Unknown  ...                       0                        0
1     Unknown  ...                       0                        0
2     Unknown  ...                       0                        0

  Target_Name_Has_Androgen  Target_Name_Has_Cytochrome  \
0                        0                           0
1                        0                           0
2                        0                           0

   Target_Name_Has_Plasmodium Target_Name_Has_Yeast  \
0                           0                     0
1                           0                     0
2                           0                     0

   Bioassay_Source_Has_Tox21  Bioassay_Source_Has_ChEMBL  \
0                          0                           0
1                          0                           0
2                          0                           0

  Bioassay_Source_Has_DTP_NCI  activityBinary
0                           0               1
1                           0               1
2                           0               1

[3 rows x 65 columns], feature_columns=['C_count', 'H_count', 'N_count', 'O_count', 'bond_count_total', 'mol_weight', 'has_chiral_center', 'Aid_Type_Encoded', 'Activity_Type_Encoded', 'Bioassay_Data_Source_Encoded', 'Has_Dose_Response_Curve', 'RNAi_BioAssay', 'Taxonomy_ID_Numeric', 'Target_Taxonomy_ID_Numeric', 'Has_Protein_Accession', 'Has_Gene_ID', 'Has_PMID', 'Has_Activity_Value', 'BioAssay_Name_Has_qHTS', 'BioAssay_Name_Has_IC50', 'BioAssay_Name_Has_Counter_Screen', 'BioAssay_Name_Has_Estrogen', 'BioAssay_Name_Has_Androgen', 'BioAssay_Name_Has_Cytochrome', 'BioAssay_Name_Has_Plasmodium', 'BioAssay_Name_Has_Yeast', 'Target_Name_Has_Estrogen', 'Target_Name_Has_Androgen', 'Target_Name_Has_Cytochrome', 'Target_Name_Has_Plasmodium', 'Target_Name_Has_Yeast', 'Bioassay_Source_Has_Tox21', 'Bioassay_Source_Has_ChEMBL', 'Bioassay_Source_Has_DTP_NCI'], target_column='activityBinary', description='Filtered Active vs Inactive assay rows using constant molecular descriptors and assay metadata.', class_names=['inactive', 'active'])

{'status': 'insufficient_data',
 'dataset': {'name': 'bioactivity-active-vs-inactive',
  'task_type': 'classification',
  'row_count': 3,
  'feature_count': 34,
  'feature_columns': ['C_count',
   'H_count',
   'N_count',
   'O_count',
   'bond_count_total',
   'mol_weight',
   'has_chiral_center',
   'Aid_Type_Encoded',
   'Activity_Type_Encoded',
   'Bioassay_Data_Source_Encoded',
   'Has_Dose_Response_Curve',
   'RNAi_BioAssay',
   'Taxonomy_ID_Numeric',
   'Target_Taxonomy_ID_Numeric',
   'Has_Protein_Accession',
   'Has_Gene_ID',
   'Has_PMID',
   'Has_Activity_Value',
   'BioAssay_Name_Has_qHTS',
   'BioAssay_Name_Has_IC50',
   'BioAssay_Name_Has_Counter_Screen',
   'BioAssay_Name_Has_Estrogen',
   'BioAssay_Name_Has_Androgen',
   'BioAssay_Name_Has_Cytochrome',
   'BioAssay_Name_Has_Plasmodium',
   'BioAssay_Name_Has_Yeast',
   'Target_Name_Has_Estrogen',
   'Target_Name_Has_Androgen',
   'Target_Name_Has_Cytochrome',
   'Target_Name_Has_Plasmodium',
   'Target_Name_Has_Yeast',
   'Bioassay_Source_Has_Tox21',
   'Bioassay_Source_Has_ChEMBL',
   'Bioassay_Source_Has_DTP_NCI'],
  'target_column': 'activityBinary',
  'class_names': ['inactive', 'active'],
  'description': 'Filtered Active vs Inactive assay rows using constant molecular descriptors and assay metadata.'},
 'reason': 'SVM requires at least two target classes.',
 'observed_class_count': 1}

## KNN

In [2]:
from ml.datasets import build_atom_heavy_atom_dataset
from ml.sklearn_workflows import run_knn

atom_heavy_dataset = build_atom_heavy_atom_dataset()
display(atom_heavy_dataset)
atom_heavy_dataset.frame.to_csv(output_directory / "cid4_ml.atom_heavy_knn_classification.csv", index=False)
knn_classification = run_knn(atom_heavy_dataset)
knn_classification

PreparedDataset(name='atom-heavy-vs-hydrogen', task_type='classification', frame=   atomLabel  bondCount  totalHydrogenCount  valency    mass  \
0         O1          2                   0        2  15.999
1         N2          3                   0        3  14.007
2         C3          4                   0        4  12.011
3         C4          4                   0        4  12.011
4         C5          4                   0        4  12.011
5         H6          1                   0        1   1.008
6         H7          1                   0        1   1.008
7         H8          1                   0        1   1.008
8         H9          1                   0        1   1.008
9        H10          1                   0        1   1.008
10       H11          1                   0        1   1.008
11       H12          1                   0        1   1.008
12       H13          1                   0        1   1.008
13       H14          1                   0        1   1.008

    hybridizationEncoded  isAromaticInt  charge  isHeavyAtom
0                      1              0       0            1
1                      1              0       0            1
2                      1              0       0            1
3                      1              0       0            1
4                      1              0       0            1
5                      0              0       0            0
6                      0              0       0            0
7                      0              0       0            0
8                      0              0       0            0
9                      0              0       0            0
10                     0              0       0            0
11                     0              0       0            0
12                     0              0       0            0
13                     0              0       0            0  , feature_columns=['bondCount', 'totalHydrogenCount', 'valency', 'mass', 'hybridizationEncoded', 'isAromaticInt', 'charge'], target_column='isHeavyAtom', description='Atom-level binary classification from conformer-derived RDKit features.', class_names=['hydrogen', 'heavy_atom'])

{'dataset': {'name': 'atom-heavy-vs-hydrogen',
  'task_type': 'classification',
  'row_count': 14,
  'feature_count': 7,
  'feature_columns': ['bondCount',
   'totalHydrogenCount',
   'valency',
   'mass',
   'hybridizationEncoded',
   'isAromaticInt',
   'charge'],
  'target_column': 'isHeavyAtom',
  'class_names': ['hydrogen', 'heavy_atom'],
  'description': 'Atom-level binary classification from conformer-derived RDKit features.'},
 'evaluation_note': 'Evaluation uses a deterministic holdout split.',
 'metrics': {'accuracy': 1.0,
  'macro_f1': 1.0,
  'confusion_matrix': [[3, 0], [0, 2]],
  'class_names': ['hydrogen', 'heavy_atom']},
 'k_neighbors': 3}

In [3]:
from ml.sklearn_workflows import run_atom_neighbor_report

knn_neighbors = run_atom_neighbor_report(atom_heavy_dataset)
knn_neighbors

{'dataset': {'name': 'atom-heavy-vs-hydrogen',
  'task_type': 'classification',
  'row_count': 14,
  'feature_count': 7,
  'feature_columns': ['bondCount',
   'totalHydrogenCount',
   'valency',
   'mass',
   'hybridizationEncoded',
   'isAromaticInt',
   'charge'],
  'target_column': 'isHeavyAtom',
  'class_names': ['hydrogen', 'heavy_atom'],
  'description': 'Atom-level binary classification from conformer-derived RDKit features.'},
 'query_atom': 'O1',
 'neighbors': [{'atom': 'O1', 'distance': 0.0},
  {'atom': 'N2', 'distance': 2.4429621364237315},
  {'atom': 'C4', 'distance': 4.88918643538984},
  {'atom': 'C3', 'distance': 4.88918643538984}]}

## Decision tree

In [2]:
from ml.datasets import build_bioactivity_binary_classification_dataset
from ml.sklearn_workflows import run_decision_tree

bioactivity_dataset = build_bioactivity_binary_classification_dataset()
display(bioactivity_dataset)
run_decision_tree(bioactivity_dataset)

PreparedDataset(name='bioactivity-active-vs-inactive', task_type='classification', frame=   Bioactivity_ID Aid_Type Activity Protein_Accession Activity_Type  \
0        32761399    Other   Active               NaN       Unknown
1       351848396    Other   Active               NaN       Unknown
2       351848428    Other   Active               NaN       Unknown

  Activity_Qualifier                               Bioassay_Data_Source  \
0                NaN                                         EPA DSSTox
1                NaN  Chemical Carcinogenesis Research Information S...
2                NaN  Chemical Carcinogenesis Research Information S...

                                       BioAssay_Name       Compound_Name  \
0  DSSTox (EPAFHM) EPA Fathead Minnow Acute Toxicity  1-Amino-2-propanol
1                         CCRIS mutagenicity studies  1-Amino-2-propanol
2                         CCRIS mutagenicity studies  1-Amino-2-propanol

  Target_Name  ... BioAssay_Name_Has_Yeast Target_Name_Has_Estrogen  \
0     Unknown  ...                       0                        0
1     Unknown  ...                       0                        0
2     Unknown  ...                       0                        0

  Target_Name_Has_Androgen  Target_Name_Has_Cytochrome  \
0                        0                           0
1                        0                           0
2                        0                           0

   Target_Name_Has_Plasmodium Target_Name_Has_Yeast  \
0                           0                     0
1                           0                     0
2                           0                     0

   Bioassay_Source_Has_Tox21  Bioassay_Source_Has_ChEMBL  \
0                          0                           0
1                          0                           0
2                          0                           0

  Bioassay_Source_Has_DTP_NCI  activityBinary
0                           0               1
1                           0               1
2                           0               1

[3 rows x 65 columns], feature_columns=['C_count', 'H_count', 'N_count', 'O_count', 'bond_count_total', 'mol_weight', 'has_chiral_center', 'Aid_Type_Encoded', 'Activity_Type_Encoded', 'Bioassay_Data_Source_Encoded', 'Has_Dose_Response_Curve', 'RNAi_BioAssay', 'Taxonomy_ID_Numeric', 'Target_Taxonomy_ID_Numeric', 'Has_Protein_Accession', 'Has_Gene_ID', 'Has_PMID', 'Has_Activity_Value', 'BioAssay_Name_Has_qHTS', 'BioAssay_Name_Has_IC50', 'BioAssay_Name_Has_Counter_Screen', 'BioAssay_Name_Has_Estrogen', 'BioAssay_Name_Has_Androgen', 'BioAssay_Name_Has_Cytochrome', 'BioAssay_Name_Has_Plasmodium', 'BioAssay_Name_Has_Yeast', 'Target_Name_Has_Estrogen', 'Target_Name_Has_Androgen', 'Target_Name_Has_Cytochrome', 'Target_Name_Has_Plasmodium', 'Target_Name_Has_Yeast', 'Bioassay_Source_Has_Tox21', 'Bioassay_Source_Has_ChEMBL', 'Bioassay_Source_Has_DTP_NCI'], target_column='activityBinary', description='Filtered Active vs Inactive assay rows using constant molecular descriptors and assay metadata.', class_names=['inactive', 'active'])

{'status': 'insufficient_data',
 'dataset': {'name': 'bioactivity-active-vs-inactive',
  'task_type': 'classification',
  'row_count': 3,
  'feature_count': 34,
  'feature_columns': ['C_count',
   'H_count',
   'N_count',
   'O_count',
   'bond_count_total',
   'mol_weight',
   'has_chiral_center',
   'Aid_Type_Encoded',
   'Activity_Type_Encoded',
   'Bioassay_Data_Source_Encoded',
   'Has_Dose_Response_Curve',
   'RNAi_BioAssay',
   'Taxonomy_ID_Numeric',
   'Target_Taxonomy_ID_Numeric',
   'Has_Protein_Accession',
   'Has_Gene_ID',
   'Has_PMID',
   'Has_Activity_Value',
   'BioAssay_Name_Has_qHTS',
   'BioAssay_Name_Has_IC50',
   'BioAssay_Name_Has_Counter_Screen',
   'BioAssay_Name_Has_Estrogen',
   'BioAssay_Name_Has_Androgen',
   'BioAssay_Name_Has_Cytochrome',
   'BioAssay_Name_Has_Plasmodium',
   'BioAssay_Name_Has_Yeast',
   'Target_Name_Has_Estrogen',
   'Target_Name_Has_Androgen',
   'Target_Name_Has_Cytochrome',
   'Target_Name_Has_Plasmodium',
   'Target_Name_Has_Yeast',
   'Bioassay_Source_Has_Tox21',
   'Bioassay_Source_Has_ChEMBL',
   'Bioassay_Source_Has_DTP_NCI'],
  'target_column': 'activityBinary',
  'class_names': ['inactive', 'active'],
  'description': 'Filtered Active vs Inactive assay rows using constant molecular descriptors and assay metadata.'},
 'reason': 'Decision tree classification requires at least two target classes.',
 'observed_class_count': 1}

## Random forest

In [2]:
from ml.datasets import build_bioactivity_binary_classification_dataset
from ml.sklearn_workflows import run_random_forest

bioactivity_dataset = build_bioactivity_binary_classification_dataset()
display(bioactivity_dataset)
run_random_forest(bioactivity_dataset)

PreparedDataset(name='bioactivity-active-vs-inactive', task_type='classification', frame=   Bioactivity_ID Aid_Type Activity Protein_Accession Activity_Type  \
0        32761399    Other   Active               NaN       Unknown
1       351848396    Other   Active               NaN       Unknown
2       351848428    Other   Active               NaN       Unknown

  Activity_Qualifier                               Bioassay_Data_Source  \
0                NaN                                         EPA DSSTox
1                NaN  Chemical Carcinogenesis Research Information S...
2                NaN  Chemical Carcinogenesis Research Information S...

                                       BioAssay_Name       Compound_Name  \
0  DSSTox (EPAFHM) EPA Fathead Minnow Acute Toxicity  1-Amino-2-propanol
1                         CCRIS mutagenicity studies  1-Amino-2-propanol
2                         CCRIS mutagenicity studies  1-Amino-2-propanol

  Target_Name  ... BioAssay_Name_Has_Yeast Target_Name_Has_Estrogen  \
0     Unknown  ...                       0                        0
1     Unknown  ...                       0                        0
2     Unknown  ...                       0                        0

  Target_Name_Has_Androgen  Target_Name_Has_Cytochrome  \
0                        0                           0
1                        0                           0
2                        0                           0

   Target_Name_Has_Plasmodium Target_Name_Has_Yeast  \
0                           0                     0
1                           0                     0
2                           0                     0

   Bioassay_Source_Has_Tox21  Bioassay_Source_Has_ChEMBL  \
0                          0                           0
1                          0                           0
2                          0                           0

  Bioassay_Source_Has_DTP_NCI  activityBinary
0                           0               1
1                           0               1
2                           0               1

[3 rows x 65 columns], feature_columns=['C_count', 'H_count', 'N_count', 'O_count', 'bond_count_total', 'mol_weight', 'has_chiral_center', 'Aid_Type_Encoded', 'Activity_Type_Encoded', 'Bioassay_Data_Source_Encoded', 'Has_Dose_Response_Curve', 'RNAi_BioAssay', 'Taxonomy_ID_Numeric', 'Target_Taxonomy_ID_Numeric', 'Has_Protein_Accession', 'Has_Gene_ID', 'Has_PMID', 'Has_Activity_Value', 'BioAssay_Name_Has_qHTS', 'BioAssay_Name_Has_IC50', 'BioAssay_Name_Has_Counter_Screen', 'BioAssay_Name_Has_Estrogen', 'BioAssay_Name_Has_Androgen', 'BioAssay_Name_Has_Cytochrome', 'BioAssay_Name_Has_Plasmodium', 'BioAssay_Name_Has_Yeast', 'Target_Name_Has_Estrogen', 'Target_Name_Has_Androgen', 'Target_Name_Has_Cytochrome', 'Target_Name_Has_Plasmodium', 'Target_Name_Has_Yeast', 'Bioassay_Source_Has_Tox21', 'Bioassay_Source_Has_ChEMBL', 'Bioassay_Source_Has_DTP_NCI'], target_column='activityBinary', description='Filtered Active vs Inactive assay rows using constant molecular descriptors and assay metadata.', class_names=['inactive', 'active'])

{'status': 'insufficient_data',
 'dataset': {'name': 'bioactivity-active-vs-inactive',
  'task_type': 'classification',
  'row_count': 3,
  'feature_count': 34,
  'feature_columns': ['C_count',
   'H_count',
   'N_count',
   'O_count',
   'bond_count_total',
   'mol_weight',
   'has_chiral_center',
   'Aid_Type_Encoded',
   'Activity_Type_Encoded',
   'Bioassay_Data_Source_Encoded',
   'Has_Dose_Response_Curve',
   'RNAi_BioAssay',
   'Taxonomy_ID_Numeric',
   'Target_Taxonomy_ID_Numeric',
   'Has_Protein_Accession',
   'Has_Gene_ID',
   'Has_PMID',
   'Has_Activity_Value',
   'BioAssay_Name_Has_qHTS',
   'BioAssay_Name_Has_IC50',
   'BioAssay_Name_Has_Counter_Screen',
   'BioAssay_Name_Has_Estrogen',
   'BioAssay_Name_Has_Androgen',
   'BioAssay_Name_Has_Cytochrome',
   'BioAssay_Name_Has_Plasmodium',
   'BioAssay_Name_Has_Yeast',
   'Target_Name_Has_Estrogen',
   'Target_Name_Has_Androgen',
   'Target_Name_Has_Cytochrome',
   'Target_Name_Has_Plasmodium',
   'Target_Name_Has_Yeast',
   'Bioassay_Source_Has_Tox21',
   'Bioassay_Source_Has_ChEMBL',
   'Bioassay_Source_Has_DTP_NCI'],
  'target_column': 'activityBinary',
  'class_names': ['inactive', 'active'],
  'description': 'Filtered Active vs Inactive assay rows using constant molecular descriptors and assay metadata.'},
 'reason': 'Random forest classification requires at least two target classes.',
 'observed_class_count': 1}


## K-Means

In [3]:
from ml.datasets import build_atom_feature_frame
from ml.sklearn_workflows import run_kmeans

atom_feature_df, _ = build_atom_feature_frame()
display(atom_feature_df)
atom_feature_df.to_csv(output_directory / "cid4_ml.atom_features.csv", index=False)
run_kmeans(atom_feature_df)

,moleculeIndex,index,bondCount,charge,implicitHydrogenCount,totalHydrogenCount,atomicNumber,symbol,valency,isAromatic,mass,hybridization,properties,atomId,hybridizationEncoded,isAromaticInt,isHeavyAtom,elementLabel,atomLabel
0,0,0,2,0,0,0,8,O,2,False,15.999,SP3,"{'__computedProps': ['_CIPRank'], '_CIPRank': 9}",1,1,0,1,O,O1
1,0,1,3,0,0,0,7,N,3,False,14.007,SP3,"{'__computedProps': ['_CIPRank'], '_CIPRank': 8}",2,1,0,1,N,N2
2,0,2,4,0,0,0,6,C,4,False,12.011,SP3,"{'molParity': 1, '_NonExplicit3DChirality': 1,...",3,1,0,1,C,C3
3,0,3,4,0,0,0,6,C,4,False,12.011,SP3,"{'_NonExplicit3DChirality': 1, '__computedProp...",4,1,0,1,C,C4
4,0,4,4,0,0,0,6,C,4,False,12.011,SP3,"{'_NonExplicit3DChirality': 1, '__computedProp...",5,1,0,1,C,C5
5,0,5,1,0,0,0,1,H,1,False,1.008,S,"{'__computedProps': ['_CIPRank'], '_CIPRank': 2}",6,0,0,0,H,H6
6,0,6,1,0,0,0,1,H,1,False,1.008,S,"{'__computedProps': ['_CIPRank'], '_CIPRank': 1}",7,0,0,0,H,H7
7,0,7,1,0,0,0,1,H,1,False,1.008,S,"{'__computedProps': ['_CIPRank'], '_CIPRank': 1}",8,0,0,0,H,H8
8,0,8,1,0,0,0,1,H,1,False,1.008,S,"{'__computedProps': ['_CIPRank'], '_CIPRank': 0}",9,0,0,0,H,H9
9,0,9,1,0,0,0,1,H,1,False,1.008,S,"{'__computedProps': ['_CIPRank'], '_CIPRank': 0}",10,0,0,0,H,H10
10,0,10,1,0,0,0,1,H,1,False,1.008,S,"{'__computedProps': ['_CIPRank'], '_CIPRank': 0}",11,0,0,0,H,H11
11,0,11,1,0,0,0,1,H,1,False,1.008,S,"{'__computedProps': ['_CIPRank'], '_CIPRank': 3}",12,0,0,0,H,H12
12,0,12,1,0,0,0,1,H,1,False,1.008,S,"{'__computedProps': ['_CIPRank'], '_CIPRank': 3}",13,0,0,0,H,H13
13,0,13,1,0,0,0,1,H,1,False,1.008,S,"{'__computedProps': ['_CIPRank'], '_CIPRank': 4}",14,0,0,0,H,H14

{'status': 'ok',
 'feature_columns': ['atomicNumber', 'mass', 'bondCount'],
 'silhouette_score': 0.8571428571428571,
 'cluster_assignments': [{'atomLabel': 'O1', 'symbol': 'O', 'cluster': 2},
  {'atomLabel': 'N2', 'symbol': 'N', 'cluster': 3},
  {'atomLabel': 'C3', 'symbol': 'C', 'cluster': 1},
  {'atomLabel': 'C4', 'symbol': 'C', 'cluster': 1},
  {'atomLabel': 'C5', 'symbol': 'C', 'cluster': 1},
  {'atomLabel': 'H6', 'symbol': 'H', 'cluster': 0},
  {'atomLabel': 'H7', 'symbol': 'H', 'cluster': 0},
  {'atomLabel': 'H8', 'symbol': 'H', 'cluster': 0},
  {'atomLabel': 'H9', 'symbol': 'H', 'cluster': 0},
  {'atomLabel': 'H10', 'symbol': 'H', 'cluster': 0},
  {'atomLabel': 'H11', 'symbol': 'H', 'cluster': 0},
  {'atomLabel': 'H12', 'symbol': 'H', 'cluster': 0},
  {'atomLabel': 'H13', 'symbol': 'H', 'cluster': 0},
  {'atomLabel': 'H14', 'symbol': 'H', 'cluster': 0}],
 'cluster_centers': [[1.0, 1.008000000000001, 0.9999999999999998],
  [6.0, 12.011, 4.0],
  [8.0, 15.999000000000002, 2.0],
  [7.0, 14.007000000000001, 3.0]]}

## Hierarchical Clustering

In [3]:
from ml.datasets import build_taxonomy_clustering_frame
from ml.sklearn_workflows import run_hierarchical_clustering

taxonomy_frame = build_taxonomy_clustering_frame()
display(taxonomy_frame)
taxonomy_frame.to_csv(output_directory / "cid4_ml.taxonomy_features.csv", index=False)

run_hierarchical_clustering()

,Source_Organism,Taxonomy,Taxonomy_ID,animalClass
0,Gallus gallus,Gallus gallus (chicken),9031,bird
1,Dromaius novaehollandiae,Dromaius novaehollandiae (emu),8790,bird
2,Struthio camelus,Struthio camelus (African ostrich),8801,bird
3,Ovis aries,Ovis aries (sheep),9940,mammal
4,Bos taurus,Bos taurus (domestic cattle),9913,mammal
5,Bos taurus X Bison bison,Bos taurus x Bison bison (beefalo),297284,mammal
6,Lepus timidus,Lepus timidus (Mountain hare),62621,mammal
7,Sus scrofa,Sus scrofa (pig),9823,mammal
8,Anas platyrhynchos,Anas platyrhynchos (mallard),8839,bird
9,Numida meleagris,Numida meleagris (helmeted guineafowl),8996,bird
10,Phasianus colchicus,Phasianus colchicus (ring-necked pheasant),9054,bird
11,Columba,Columba,8931,bird
12,Leporidae,Leporidae (rabbits and hares),9979,mammal
13,Phasianidae,Phasianidae (turkeys),9005,bird
14,Columbidae,Columbidae (pigeons),8930,bird
15,Bubalus bubalis,Bubalus bubalis (water buffalo),89462,mammal
16,Cervus canadensis,Cervus canadensis (elk),1574408,mammal
17,Equus caballus,Equus caballus (horse),9796,mammal
18,Oryctolagus,Oryctolagus,9984,mammal
19,Meleagris gallopavo,Meleagris gallopavo (turkey),9103,bird
20,Capra aegagrus hircus,Capra hircus (goat),9925,mammal
21,Anatidae,Anatidae (waterfowl),8830,bird
22,Bison bison,Bison bison (American bison),9901,mammal
23,Odocoileus,Odocoileus,9871,mammal
24,Anser anser,Anser anser (Domestic goose),8843,bird
25,Melanitta fusca,Melanitta fusca (velvet scoter),371864,bird
26,Cervidae,Cervidae (deer),9850,mammal
27,Sus scrofa domestica,Sus scrofa domesticus (domestic pig),9825,mammal
28,Lagopus muta,Lagopus muta (rock ptarmigan),64668,bird

{'row_count': 29,
 'cluster_assignments': [{'Source_Organism': 'Gallus gallus',
   'Taxonomy': 'Gallus gallus (chicken)',
   'Taxonomy_ID': 9031,
   'animalClass': 'bird',
   'cluster': 0},
  {'Source_Organism': 'Dromaius novaehollandiae',
   'Taxonomy': 'Dromaius novaehollandiae (emu)',
   'Taxonomy_ID': 8790,
   'animalClass': 'bird',
   'cluster': 0},
  {'Source_Organism': 'Struthio camelus',
   'Taxonomy': 'Struthio camelus (African ostrich)',
   'Taxonomy_ID': 8801,
   'animalClass': 'bird',
   'cluster': 0},
  {'Source_Organism': 'Ovis aries',
   'Taxonomy': 'Ovis aries (sheep)',
   'Taxonomy_ID': 9940,
   'animalClass': 'mammal',
   'cluster': 0},
  {'Source_Organism': 'Bos taurus',
   'Taxonomy': 'Bos taurus (domestic cattle)',
   'Taxonomy_ID': 9913,
   'animalClass': 'mammal',
   'cluster': 0},
  {'Source_Organism': 'Bos taurus X Bison bison',
   'Taxonomy': 'Bos taurus x Bison bison (beefalo)',
   'Taxonomy_ID': 297284,
   'animalClass': 'mammal',
   'cluster': 0},
  {'Source_Organism': 'Lepus timidus',
   'Taxonomy': 'Lepus timidus (Mountain hare)',
   'Taxonomy_ID': 62621,
   'animalClass': 'mammal',
   'cluster': 0},
  {'Source_Organism': 'Sus scrofa',
   'Taxonomy': 'Sus scrofa (pig)',
   'Taxonomy_ID': 9823,
   'animalClass': 'mammal',
   'cluster': 0},
  {'Source_Organism': 'Anas platyrhynchos',
   'Taxonomy': 'Anas platyrhynchos (mallard)',
   'Taxonomy_ID': 8839,
   'animalClass': 'bird',
   'cluster': 0},
  {'Source_Organism': 'Numida meleagris',
   'Taxonomy': 'Numida meleagris (helmeted guineafowl)',
   'Taxonomy_ID': 8996,
   'animalClass': 'bird',
   'cluster': 0},
  {'Source_Organism': 'Phasianus colchicus',
   'Taxonomy': 'Phasianus colchicus (ring-necked pheasant)',
   'Taxonomy_ID': 9054,
   'animalClass': 'bird',
   'cluster': 0},
  {'Source_Organism': 'Columba',
   'Taxonomy': 'Columba',
   'Taxonomy_ID': 8931,
   'animalClass': 'bird',
   'cluster': 0},
  {'Source_Organism': 'Leporidae',
   'Taxonomy': 'Leporidae (rabbits and hares)',
   'Taxonomy_ID': 9979,
   'animalClass': 'mammal',
   'cluster': 0},
  {'Source_Organism': 'Phasianidae',
   'Taxonomy': 'Phasianidae (turkeys)',
   'Taxonomy_ID': 9005,
   'animalClass': 'bird',
   'cluster': 0},
  {'Source_Organism': 'Columbidae',
   'Taxonomy': 'Columbidae (pigeons)',
   'Taxonomy_ID': 8930,
   'animalClass': 'bird',
   'cluster': 0},
  {'Source_Organism': 'Bubalus bubalis',
   'Taxonomy': 'Bubalus bubalis (water buffalo)',
   'Taxonomy_ID': 89462,
   'animalClass': 'mammal',
   'cluster': 0},
  {'Source_Organism': 'Cervus canadensis',
   'Taxonomy': 'Cervus canadensis (elk)',
   'Taxonomy_ID': 1574408,
   'animalClass': 'mammal',
   'cluster': 1},
  {'Source_Organism': 'Equus caballus',
   'Taxonomy': 'Equus caballus (horse)',
   'Taxonomy_ID': 9796,
   'animalClass': 'mammal',
   'cluster': 0},
  {'Source_Organism': 'Oryctolagus',
   'Taxonomy': 'Oryctolagus',
   'Taxonomy_ID': 9984,
   'animalClass': 'mammal',
   'cluster': 0},
  {'Source_Organism': 'Meleagris gallopavo',
   'Taxonomy': 'Meleagris gallopavo (turkey)',
   'Taxonomy_ID': 9103,
   'animalClass': 'bird',
   'cluster': 0},
  {'Source_Organism': 'Capra aegagrus hircus',
   'Taxonomy': 'Capra hircus (goat)',
   'Taxonomy_ID': 9925,
   'animalClass': 'mammal',
   'cluster': 0},
  {'Source_Organism': 'Anatidae',
   'Taxonomy': 'Anatidae (waterfowl)',
   'Taxonomy_ID': 8830,
   'animalClass': 'bird',
   'cluster': 0},
  {'Source_Organism': 'Bison bison',
   'Taxonomy': 'Bison bison (American bison)',
   'Taxonomy_ID': 9901,
   'animalClass': 'mammal',
   'cluster': 0},
  {'Source_Organism': 'Odocoileus',
   'Taxonomy': 'Odocoileus',
   'Taxonomy_ID': 9871,
   'animalClass': 'mammal',
   'cluster': 0},
  {'Source_Organism': 'Anser anser',
   'Taxonomy': 'Anser anser (Domestic goose)',
   'Taxonomy_ID': 8843,
   'animalClass': 'bird',
   'cluster': 0},
  {'Source_Organism': 'Melanitta fusca',
   'Taxonomy': 'Melanitta fusca (velvet scoter)',
   'Taxonomy_ID': 371864,
   'animalClass': 'bird',
   'cluster': 0},
  {'Source_Organism': 'Cervidae',
   'Taxonomy': 'Cervidae (deer)',
   'Taxonomy_ID': 9850,
   'animalClass': 'mammal',
   'cluster': 0},
  {'Source_Organism': 'Sus scrofa domestica',
   'Taxonomy': 'Sus scrofa domesticus (domestic pig)',
   'Taxonomy_ID': 9825,
   'animalClass': 'mammal',
   'cluster': 0},
  {'Source_Organism': 'Lagopus muta',
   'Taxonomy': 'Lagopus muta (rock ptarmigan)',
   'Taxonomy_ID': 64668,
   'animalClass': 'bird',
   'cluster': 0}],
 'class_breakdown': [{'cluster': 0, 'animalClass': 'bird', 'count': 14},
  {'cluster': 0, 'animalClass': 'mammal', 'count': 14},
  {'cluster': 1, 'animalClass': 'mammal', 'count': 1}],
 'linkage_preview': [[11.0, 14.0, 1.0, 2.0],
  [7.0, 27.0, 2.0, 2.0],
  [8.0, 24.0, 4.0, 2.0],
  [12.0, 18.0, 5.0, 2.0],
  [9.0, 13.0, 9.0, 2.0],
  [1.0, 2.0, 11.0, 2.0],
  [4.0, 20.0, 12.0, 2.0],
  [21.0, 31.0, 12.701705922171765, 3.0]]}


## PCA

In [2]:
from ml.datasets import build_heavy_atom_pca_dataset
from ml.sklearn_workflows import run_pca

heavy_atom_pca_dataset = build_heavy_atom_pca_dataset()
display(heavy_atom_pca_dataset)
run_pca(heavy_atom_pca_dataset)

PreparedDataset(name='heavy-atom-pca', task_type='embedding', frame=  atomLabel  atomicNumber  bondCount  totalHydrogenCount  valency    mass  \
0        O1             8          2                   0        2  15.999
1        N2             7          3                   0        3  14.007
2        C3             6          4                   0        4  12.011
3        C4             6          4                   0        4  12.011
4        C5             6          4                   0        4  12.011

   hybridizationEncoded  isAromaticInt
0                     1              0
1                     1              0
2                     1              0
3                     1              0
4                     1              0  , feature_columns=['atomicNumber', 'bondCount', 'totalHydrogenCount', 'valency', 'mass', 'hybridizationEncoded', 'isAromaticInt'], target_column=None, description='Heavy-atom feature matrix for PCA and related unsupervised analysis.', class_names=None)

{'dataset': {'name': 'heavy-atom-pca',
  'task_type': 'embedding',
  'row_count': 5,
  'feature_count': 7,
  'feature_columns': ['atomicNumber',
   'bondCount',
   'totalHydrogenCount',
   'valency',
   'mass',
   'hybridizationEncoded',
   'isAromaticInt'],
  'target_column': None,
  'class_names': None,
  'description': 'Heavy-atom feature matrix for PCA and related unsupervised analysis.'},
 'explained_variance_ratio': [0.9999999422235468, 5.7776453170966324e-08],
 'loadings': [{'feature': 'atomicNumber',
   'pc1': 0.3785860230080681,
   'pc2': -0.4358967268934349},
  {'feature': 'bondCount',
   'pc1': -0.3785860230080681,
   'pc2': 0.43589672689319064},
  {'feature': 'totalHydrogenCount', 'pc1': 0.0, 'pc2': -0.0},
  {'feature': 'valency',
   'pc1': -0.3785860230080681,
   'pc2': 0.4358967268931907},
  {'feature': 'mass', 'pc1': 0.7549952778321223, 'pc2': 0.6557302268854139},
  {'feature': 'hybridizationEncoded', 'pc1': 0.0, 'pc2': -0.0},
  {'feature': 'isAromaticInt', 'pc1': 0.0, 'pc2': -0.0}],
 'scores': [{'row': 'O1',
   'pc1': 3.6974041161189084,
   'pc2': -0.0004920436691731763},
  {'row': 'N2', 'pc1': 1.0576954536531156, 'pc2': 0.0009835250548980107},
  {'row': 'C3', 'pc1': -1.585033189924005, 'pc2': -0.00016382712857239848},
  {'row': 'C4', 'pc1': -1.585033189924005, 'pc2': -0.00016382712857239848},
  {'row': 'C5', 'pc1': -1.585033189924005, 'pc2': -0.00016382712857239848}]}

## Naive Bayes

In [2]:
from ml.datasets import build_atom_heavy_atom_dataset
from ml.sklearn_workflows import run_naive_bayes

atom_heavy_dataset = build_atom_heavy_atom_dataset()
display(atom_heavy_dataset)
run_naive_bayes(atom_heavy_dataset)

PreparedDataset(name='atom-heavy-vs-hydrogen', task_type='classification', frame=   atomLabel  bondCount  totalHydrogenCount  valency    mass  \
0         O1          2                   0        2  15.999
1         N2          3                   0        3  14.007
2         C3          4                   0        4  12.011
3         C4          4                   0        4  12.011
4         C5          4                   0        4  12.011
5         H6          1                   0        1   1.008
6         H7          1                   0        1   1.008
7         H8          1                   0        1   1.008
8         H9          1                   0        1   1.008
9        H10          1                   0        1   1.008
10       H11          1                   0        1   1.008
11       H12          1                   0        1   1.008
12       H13          1                   0        1   1.008
13       H14          1                   0        1   1.008

    hybridizationEncoded  isAromaticInt  charge  isHeavyAtom
0                      1              0       0            1
1                      1              0       0            1
2                      1              0       0            1
3                      1              0       0            1
4                      1              0       0            1
5                      0              0       0            0
6                      0              0       0            0
7                      0              0       0            0
8                      0              0       0            0
9                      0              0       0            0
10                     0              0       0            0
11                     0              0       0            0
12                     0              0       0            0
13                     0              0       0            0  , feature_columns=['bondCount', 'totalHydrogenCount', 'valency', 'mass', 'hybridizationEncoded', 'isAromaticInt', 'charge'], target_column='isHeavyAtom', description='Atom-level binary classification from conformer-derived RDKit features.', class_names=['hydrogen', 'heavy_atom'])

{'dataset': {'name': 'atom-heavy-vs-hydrogen',
  'task_type': 'classification',
  'row_count': 14,
  'feature_count': 7,
  'feature_columns': ['bondCount',
   'totalHydrogenCount',
   'valency',
   'mass',
   'hybridizationEncoded',
   'isAromaticInt',
   'charge'],
  'target_column': 'isHeavyAtom',
  'class_names': ['hydrogen', 'heavy_atom'],
  'description': 'Atom-level binary classification from conformer-derived RDKit features.'},
 'evaluation_note': 'Evaluation uses a deterministic holdout split.',
 'metrics': {'accuracy': 1.0,
  'macro_f1': 1.0,
  'confusion_matrix': [[3, 0], [0, 2]],
  'class_names': ['hydrogen', 'heavy_atom']}}